apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  selector:
    app: django
    version: green   # Switch to "blue" to route to blue version
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
